name: nodejs application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "hacker12345" --password-stdin
        docker image build -t hacker12345/epicb1_backend:latest .
        docker push hacker12345/epicb1_backend:latest